website/models.py
from . import db
from flask_login import UserMixin
from sqlalchemy.sql import func


class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100), nullable=False)
    content = db.Column(db.Text, nullable=False)
    date_posted = db.Column(
        db.DateTime(timezone=True), nullable=False, default=func.now()
    )
    user_id = db.Column(db.Integer, db.ForeignKey("user.id"), nullable=False)
    likes = db.relationship("Like", backref="post", lazy=True)
    comments = db.relationship("Comment", backref="post", lazy=True)


class Comment(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    content = db.Column(db.Text, nullable=False)
    date_posted = db.Column(
        db.DateTime(timezone=True), nullable=False, default=func.now()
    )
    user_id = db.Column(db.Integer, db.ForeignKey("user.id"), nullable=False)
    post_id = db.Column(db.Integer, db.ForeignKey("post.id"), nullable=False)


class Like(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey("user.id"), nullable=False)
    post_id = db.Column(db.Integer, db.ForeignKey("post.id"), nullable=False)


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(150), unique=True)
    password = db.Column(db.String(150))
    first_name = db.Column(db.String(150))
    posts = db.relationship("Post", backref="user", lazy=True)
    comments = db.relationship("Comment", backref="user", lazy=True)
    likes = db.relationship("Like", backref="user", lazy=True)

website/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from os import path
from flask_login import LoginManager

db = SQLAlchemy()
DB_NAME = "database.db"


def create_app():
    app = Flask(__name__)
    app.config["SECRET_KEY"] = "hjshjhdjah kjshkjdhjs"
    app.config["SQLALCHEMY_DATABASE_URI"] = f"sqlite:///{DB_NAME}"
    db.init_app(app)

    from .views import views
    from .auth import auth

    app.register_blueprint(views, url_prefix="/")
    app.register_blueprint(auth, url_prefix="/")

    from .models import User, Comment, Like, Post

    with app.app_context():
        db.create_all()

    login_manager = LoginManager()
    login_manager.login_view = "auth.login"
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(id):
        return User.query.get(int(id))

    return app


def create_database(app):
    if not path.exists("website/" + DB_NAME):
        db.create_all(app=app)
        print("Created Database!")

website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import User
from werkzeug.security import generate_password_hash, check_password_hash
from . import db  ##means from __init__.py import db
from flask_login import login_user, login_required, logout_user, current_user


auth = Blueprint("auth", __name__)


@auth.route("/login", methods=["GET", "POST"])
def login():
    if request.method == "POST":
        email = request.form.get("email")
        password = request.form.get("password")

        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                flash("Logged in successfully!", category="success")
                login_user(user, remember=True)
                return redirect(url_for("views.index"))
            else:
                flash("Incorrect password, try again.", category="error")
        else:
            flash("Email does not exist.", category="error")

    return render_template("login.html", user=current_user)


@auth.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("auth.login"))


@auth.route("/sign-up", methods=["GET", "POST"])
def sign_up():
    if request.method == "POST":
        email = request.form.get("email")
        first_name = request.form.get("firstName")
        password1 = request.form.get("password1")
        password2 = request.form.get("password2")

        user = User.query.filter_by(email=email).first()
        if user:
            flash("Email already exists.", category="error")
        elif len(email) < 4:
            flash("Email must be greater than 3 characters.", category="error")
        elif len(first_name) < 2:
            flash("First name must be greater than 1 character.", category="error")
        elif password1 != password2:
            flash("Passwords don't match.", category="error")
        elif len(password1) < 7:
            flash("Password must be at least 7 characters.", category="error")
        else:
            new_user = User(
                email=email,
                first_name=first_name,
                password=generate_password_hash(password1, method="sha256"),
            )
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            flash("Account created!", category="success")
            return redirect(url_for("views.index"))

    return render_template("sign_up.html", user=current_user)

website/views.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_login import current_user, login_required
from .models import Post, Comment, Like, User
from sqlalchemy.sql import func
from markupsafe import Markup
from . import db

views = Blueprint("views", __name__)


@views.route("/", methods=["GET", "POST"])
@login_required
def index():
    if request.method == "POST":
        title = request.form.get("title")
        content = Markup(request.form.get("content"))
        if not title or not content:
            flash("Please enter a title and content for your post", category="error")
        else:
            post = Post(title=title, content=content, author=current_user)
            db.session.add(post)
            db.session.commit()
            flash("Post created!", category="success")
            return redirect(url_for("views.index"))

    posts = Post.query.order_by(Post.date_posted.desc()).all()
    return render_template("index.html", posts=posts, safe=func.safe)


@views.route("/create_post", methods=["GET", "POST"])
@login_required
def create_post():
    if request.method == "POST":
        title = request.form.get("title")
        content = Markup(request.form.get("content"))
        post = Post(title=title, content=content, user_id=current_user.id)
        db.session.add(post)
        db.session.commit()
        flash("Your post has been created!", "success")
        return redirect(url_for("views.index"))
    return render_template("create_post.html", title="Create Post")


@views.route("/like_post/<int:post_id>", methods=["GET", "POST"])
@login_required
def like_post(post_id):
    post = Post.query.get_or_404(post_id)
    like = Like.query.filter_by(post_id=post.id, user_id=current_user.id).first()
    if like:
        db.session.delete(like)
        db.session.commit()
        flash("Your like has been removed!", "success")
    else:
        like = Like(post_id=post.id, user_id=current_user.id)
        db.session.add(like)
        db.session.commit()
        flash("Your like has been added!", "success")
    return redirect(url_for("views.index"))


@views.route("/comment_post/<int:post_id>", methods=["GET", "POST"])
@login_required
def comment_post(post_id):
    post = Post.query.get_or_404(post_id)
    content = request.form.get("content")
    comment = Comment(content=content, user_id=current_user.id, post_id=post.id)
    db.session.add(comment)
    db.session.commit()
    flash("Your comment has been added!", "success")
    return redirect(url_for("views.index"))


@views.route("/delete_post/<int:post_id>", methods=["GET", "POST"])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.user_id != current_user.id:
        flash("You are not authorized to delete this post!", "danger")
        return redirect(url_for("views.index"))
    comments = Comment.query.filter_by(post_id=post_id).all()
    for comment in comments:
        db.session.delete(comment)
    likes = Like.query.filter_by(post_id=post_id).all()
    for like in likes:
        db.session.delete(like)
    db.session.delete(post)
    db.session.commit()
    flash("Your post has been deleted!", "success")
    return redirect(url_for("views.index"))

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    >
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    >
    <title>{% block title %} {% endblock %} Post-based Web App</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="collapse navbar-collapse" id="navbar">
        <div class="navbar-nav">
          {% if current_user.is_authenticated %}
            <a class="nav-item nav-link" id="home" href="{{ url_for('views.index') }}">Home</a>
            <a class="nav-item nav-link" id="logout" href="{{ url_for('auth.logout') }}">Logout</a>
          {% else %}
            <a class="nav-item nav-link" id="home" href="{{ url_for('views.index') }}">Home</a>
            <a class="nav-item nav-link" id="login" href="{{ url_for('auth.login') }}">Login</a>
            <a class="nav-item nav-link" id="signUp" href="{{ url_for('auth.sign_up') }}">Sign Up</a>
          {% endif %}
        </div>
      </div>
    </nav>
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
        {% for category, message in messages %}
        {% if category == 'error' %}
        <div class="alert alert-danger alert-dismissable fade show" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {% else %}
        <div class="alert alert-success alert-dismissable fade show" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {% endif %}
        {% endfor %}
    {% endif %}
    {% endwith %}
    <br>
    <div class="container">{% block content %} {% endblock %}</div>
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
</body>
</html>

website/templates/create_post.html
{% extends 'base.html' %}

{% block content %}
  <h1>Create Post</h1>
  <form action="{{ url_for('views.create_post') }}" method="POST">
    <div class="form-group">
      <label for="title">Title:</label>
      <input type="text" class="form-control" id="title" name="title" placeholder="Enter title">
    </div>
    <div class="form-group">
      <label for="content">Content:</label>
      <textarea class="form-control" id="content" name="content" rows="5" placeholder="Enter content"></textarea>
    </div>
    <button type="submit" class="btn btn-primary">Create</button>
  </form>
{% endblock %}

website/templates/edit.html
{% extends 'base.html' %}

{% block content %}
    <h1>{% block title %} Edit "{{ post['title'] }}" {% endblock %}</h1>
    <form method="post">
        <label for="title">Title</label>
        <br>
        <input type="text" name="title"
               placeholder="Post title"
               value="{{ request.form['title'] or post['title'] }}"></input>
        <br>

        <label for="author">Author</label>
        <br>
        <input type="text" name="author"
               placeholder="Post author"
               value="{{ request.form['author'] or post['author'] }}"></input>
        <br>

        <label for="content">Post Content</label>
        <br>
        <textarea name="content"
                  placeholder="Post content"
                  rows="15"
                  cols="60"
                  >{{ request.form['content'] or post['content'] }}</textarea>
        <br>
        <button type="submit">Submit</button>
    </form>

    <hr>
    <form action="{{ url_for('delete', id=post['id']) }}" method="POST">
        <input type="submit" value="Delete Post"
                onclick="return confirm('Are you sure you want to delete this post?')">
    </form>
{% endblock %}

website/templates/index.html
{% extends 'base.html' %}

{% block content %}
  <div class="content-section">
    <div class="media">
      <div class="media-body">
        <h2>{{ current_user.first_name }}</h2>
        <p>{{ current_user.email }}</p>
      </div>
    </div>
    <hr>
    <a class="btn btn-primary mb-3" href="{{ url_for('views.create_post') }}">Create Post</a>
    {% for post in posts %}
      <div class="card mb-3">
        <div class="card-body">
          <h4 class="card-title">{{ post.title }}</h4>
          <h6 class="card-subtitle mb-2 text-muted"> by {{ post.user.first_name }}</h6>
          <p class="card-text">{{ post.content | safe }}</p>
          <a href="{{ url_for('views.like_post', post_id=post.id) }}" class="btn btn-secondary btn-sm">
            {% if current_user in post.likes %}
              Unlike {{ post.likes | count }}
            {% else %}
              Like {{ post.likes | count }}
            {% endif %}
          </a>
          <a href="#" class="btn btn-secondary btn-sm" data-toggle="collapse" data-target="#comments-{{ post.id }}">Comments</a>
          {% if current_user == post.user %}
            <form action="{{ url_for('views.delete_post', post_id=post.id) }}" method="post" class="d-inline">
              <button type="submit" class="btn btn-danger btn-sm">Delete</button>
            </form>
          {% endif %}
          <div id="comments-{{ post.id }}" class="collapse mt-3">
            {% for comment in post.comments %}
              <div class="card mb-3">
                <div class="card-body">
                  <h6 class="card-subtitle mb-2 text-muted">{{ comment.user.first_name }} | {{ comment.date_posted.strftime('%Y-%m-%d %H:%M:%S') }}</h6>
                  <p class="card-text">{{ comment.content }}</p>
                </div>
              </div>
            {% endfor %}
            <form action="{{ url_for('views.comment_post', post_id=post.id) }}" method="post">
              <div class="form-group">
                <textarea class="form-control" name="content" placeholder="Add a comment..." required></textarea>
              </div>
              <button type="submit" class="btn btn-primary btn-sm">Post Comment</button>
            </form>
          </div>
        </div>
        <div class="card-footer text-muted">
          Posted on {{ post.date_posted.strftime('%Y-%m-%d %H:%M:%S') }}
        </div>
      </div>
    {% endfor %}
  </div>
{% endblock %}

website/templates/login.html
{% extends 'base.html' %}

{% block content %}
<form method="POST">
    <h3 align="center">Login</h3>
    <div class="form-group">
        <label for="email">Email Address</label>
        <input type="email" class="form-control" id="email" name="email", placeholder="Enter email">
    </div>
    <div class="form-group">
        <label for="password">Password</label>
        <input type="password" class="form-control" id="password" name="password", placeholder="Enter password">
    </div>
    <br>
    <button type="submit" class="btn btn-primary">Login</button>
</form>
{% endblock %}

website/templates/sign_up.html
{% extends 'base.html' %}

{% block content %}
    <form method="POST">
        <h3 align="center">Sign Up</h3>
        <div class="form-group">
            <label for="email">Email Address</label>
            <input type="email" class="form-control" id="email" name="email", placeholder="Enter email">
        </div>
        <div class="form-group">
            <label for="firstName">First Name</label>
            <input type="text" class="form-control" id="firstName" name="firstName", placeholder="Enter first name">
        </div>
        <div class="form-group">
            <label for="password1">Password</label>
            <input type="password" class="form-control" id="password1" name="password1", placeholder="Enter password">
        </div>
        <div class="form-group">
            <label for="password2">Password (Confirm)</label>
            <input type="password" class="form-control" id="password2" name="password2", placeholder="Confirm password">
        </div>
        <br>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
{% endblock %}